import type { RequestHandler } from 'express';
import type * as JSONAPI from 'jsonapi-typescript';

const docWithData = (data: JSONAPI.PrimaryData): JSONAPI.DocWithData => ({ data });

const docWithErrors = (...errors: JSONAPI.Errors): JSONAPI.DocWithErrors => ({ errors });

const JSONAPIResponseInterceptor: RequestHandler = (req, res, next) => {
  const originalSend = res.send.bind(res);

  res.send = (body) => {
    // body from res.send can be object
    // while body from res.json is string generated by JSON.stringify
    const document = typeof body === 'string' ? JSON.parse(body) : body;

    const response: JSONAPI.Document = {
      jsonapi: {
        version: '1.0',
      },
      ...document,
    };

    return originalSend(JSON.stringify(response));
  };

  res.set('Content-Type', 'application/json; charset=utf-8');

  next();
};

export {
  docWithData,
  docWithErrors,
  JSONAPIResponseInterceptor,
};
